"""empty message

Revision ID: 400d95648c70
Revises: 
Create Date: 2021-06-27 16:14:16.867648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400d95648c70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeline',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('u_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.String(length=100), nullable=False),
    sa.Column('conversation_id', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('reply_settings', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(length=4294000000), nullable=False),
    sa.Column('timeline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['u_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeline')
    op.drop_table('user')
    # ### end Alembic commands ###
