"""empty message

Revision ID: 707fe809e7a1
Revises: 400d95648c70
Create Date: 2021-06-27 16:26:59.850189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707fe809e7a1'
down_revision = '400d95648c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
